### ISSUE TITLE
AES key ladder

### ISSUE THREAD

**Issue by AlexeyGorbushin** [quarkslab/titanm#7]
The Titan M chipset has interesting hardware feature called a 'key ladder' for several algorithms. Not sure what is the primary purpose of this feature, performance of the crypto algorithms or security. I would think it is a 'security feature' if the 'trusted root key' was fused directly in the OTP area of Titan M and was not accessible from the NOS' tasks as well. If everything can be sniffed in the middle of the user land <-> the NOS task as well as application processor <-> Titan M by means of the breakout board, it doesn't look like a HSM. But it is just my personal opinion. I am not a security expert. 
Probably, below information someone can find useful:
The AES key ladder has several chipset specific registers to implement encryption/decryption.
1. Input register 'AES_WFIFO_DATA' located at 0x40230008. The register has a FIFO concept. To store the 128 bit block, it is divided on four 32-bit blocks and pushed to the same register.
2. Output register 'AES_RFIFO_DATA' located at 0x4023000C. It has the similar FIFO concept to read the processed data from the key ladder.
3. Status register 'AES_RFIFO_EMPTY' located at 0x40230070. It works like  `while ( MEMORY[0x40230070] );`
4. Control register 'AES_CTRL' located at 0x40230000. This register is used to control the key size, cipher mode, processing direction (encryption/decryption), endianness.
5. Key expansion register 'AES_KEY_START' located at 0x4023004C. Writing '1' to this register triggers key expansion. Waiting of the key expansion is performed by `while ( MEMORY[0x4023004C] );`.
6. To store the initialization vector, 'GR_KEYMGR_AES_CTR' (??? Counter mode is used?) registers are used. There are four such registers located at 0x40230050, 0x40230054, 0x40230058, 0x4023005C. 
7. @max-r-b Could you confirm that the register set '0x40233300, 0x40233304, ..., 0x40233320' are used to store the AES key? It seems these registers are also involved in HMAC computation. There is, definitely, the register 0x4023002C, ... for storing the raw AES key, but for some reasons, km_generate_key() doesn't use these registers.

**Comment by AlexeyGorbushin** [comment]
Were you able to check authenticity of the key blob successfully? Say, the 'GenerateKey' response.
The HMAC key derivation is straightforward but the calculated HMAC-SHA256 doesn't match with the blob' one.
In my case HMAC key is derived as:
```
K <- SHA256( 4BF5122F344554C53BDE2EBB8CD2B7E3D1600AD631C385A5D7CCE23C7785459A ||
             9AE23C4D136D1B8CA5702FA25420F0DDD352F204B434861F7406900C720DD589 || 
             DE264EADF51022500B583645DF288D91C5006539A8EF016B024F7E4B31CEE349 )  

K <- 3440f2c11729040b191515c5cd6445eb340cdc0ab5eb59277b05d33d82a9501b
```

The received key blob is:
```
47 4F 4F 47 02 00 00 00 00 00 00 00 8C 8C CC 20 B5 A9 F0 AF 92 2A 74 6A FF 28 7D B7 01 00 00 00
BD 02 06 00 00 00 00 00 5E 93 C4 4E 7D 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0D 00 00 00 BE 02 01 00 00 00 00 00 00 00 00 00 00 00 00 00 C1 02 03 00 B0 AD 01 00 00 00 00 00
00 00 00 00 C2 02 03 00 7E 15 03 00 00 00 00 00 00 00 00 00 CF 02 03 00 39 65 34 01 00 00 00 00
00 00 00 00 CE 02 03 00 39 65 34 01 00 00 00 00 00 00 00 00 03 00 03 00 00 01 00 00 00 00 00 00
00 00 00 00 02 00 01 00 02 00 00 00 00 00 00 00 00 00 00 00 01 00 02 00 00 00 00 00 00 00 00 00
00 00 00 00 04 00 02 00 03 00 00 00 00 00 00 00 00 00 00 00 06 00 02 00 00 00 00 00 00 00 00 00
00 00 00 00 F7 01 07 00 01 00 00 00 00 00 00 00 00 00 00 00 08 00 03 00 60 00 00 00 00 00 00 00
00 00 00 00 07 00 07 00 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00
38 D3 F7 CF 8F 1F 55 4E DC 0A 7A 76 C9 62 0B 2B C8 5B D2 B8 82 F6 2A 2F B0 9D ED CD 84 AD CC FC
D5 E4 98 F5 F3 82 D4 B5 B0 D7 A1 EB F7 26 DE B4 C0 C5 F0 65 EA 9E 5A 2E B2 63 AA 19 59 78 0D 4B
7A 5B 43 E1 1F 9B 36 E7 0C 01 F6 C3 68 7A A4 6A E5 F6 36 61 74 11 7B 8E 18 C2 2B 77 6A BF 6D 25
DD 9F BB DE 56 12 37 90 EB EE 2D A6 1C 9C BD 45 09 EF 36 3A 91 E1 B2 2C 4D CC 58 F7 F0 9C C2 78
4C 58 88 7B B0 80 B4 32 55 D7 12 60 3E 9C A7 69 BE F5 25 EA 47 7D BE 0D 7C D8 A1 D2 BD C2 B8 45
0E 3F C6 DD F1 FB 07 30 D9 62 DE DC A3 1D 31 76 1D E5 D5 D3 9F 6A 18 B4 50 7B BC 1F 45 B0 92 DC
79 D9 51 E6 EC F2 C0 9B 9A 82 28 7E 51 8E 1A B2 A4 B3 51 58 7D 59 46 CD 84 AC BB F8 A2 CC 59 93
AB B0 B4 D6 A3 38 75 81 FC 4C 8A 0A 77 F6 CC 29 38 78 43 58 0F CC 5C C4 74 0A E3 8A 67 23 AD 50
46 73 0D B9 6E 60 C5 76 A9 50 6F F1 2F F6 63 3D 49 65 98 5E 18 4B C6 E1 D0 F0 9B 5B 55 98 43 24
4B C2 9D 48 0A 6C 01 72 0C 52 C7 C0 3E F0 A4 2C DE 44 A4 2A C8 A7 5B 52 88 B4 22 E8 5D 1C D5 B7
F0 75 DC 67 3A CC 41 3D CC D2 15 78 80 BE E3 C0 23 DB DF AC 41 D8 6E 6E 59 97 34 2A AB CC B1 B2
02 23 11 CD C8 B0 2D F0 A5 42 63 A8 50 AC 50 AA 6B 24 32 11 2D DE D7 79 24 B6 8D 86 55 C0 C5 DE
E4 28 B0 CC 43 8E DE 6A 0D 41 6B 26 9F A3 DA CC 5E 00 13 C5 BE AA FD 3A 39 7D 2B FF D1 33 25 A1
01 DF 04 F2 20 F6 4A A2 38 0B 6E 7E BA 4F 9D 26 9F 96 2F F9 74 5C 85 F3 A4 7D 1A 2C 98 3F CE 28
D6 41 80 A6 9D 63 7F A4 E0 8A 6C 00 D4 89 E0 AE 39 F8 8D 83 91 86 F4 9B 3F A1 4E FB 6B 09 E5 A1
2D 63 D5 EA C6 AC 5F 48 14 42 7A C8 3A 37 1F 78 C6 DC D5 CB 57 79 CD E2 6F E4 EC 01 67 D7 18 99
7D 83 D8 87 FD 4A 33 4D 58 C8 6A 65 3B 14 C7 87 92 A7 ED A7 0E 03 B6 91 74 49 EC 69 37 C7 75 2D
E1 25 FA 7B E7 A1 05 2A 64 C6 34 F5 D0 1B 4F A1 9F 12 BA DE D3 2F 06 71 21 FB E8 85 6E D2 29 B0
FE C9 0A 16 9A 01 8B EC 1E 19 8B EE 08 C2 70 1B 74 AC CA A5 65 FA 50 6A B7 A5 34 53 5C B2 CB 78
B5 CA 0F 98 5E EB 5F E4 FA 10 09 E3 52 E3 7A A2 A9 87 D0 32 64 7D 5D 18 A7 EF C7 B9 13 AC 95 C7
32 BB A2 BD EA 6D B7 08 00 34 E4 AB 9E CD 58 B2 02 F9 0F 5E 43 15 9E 00 AE 91 62 96 5B 6F D3 8E
81 B4 B0 53 61 EA 13 86 D4 4B 29 CE 4A 54 3F 09 FD 26 3C CA C2 B1 8C B7 89 6A A4 E9 59 F5 28 BE
76 3B 8A 5B E5 90 47 70 B5 DA FB 5C 3D 5E 46 6F E6 56 B8 7F CA 46 7B 3F 12 4F F1 D3 BB 97 54 9E
C0 13 5E 14 50 81 F1 99 57 28 74 79 0C 17 D5 89 9D 0D C2 CC 2A 08 66 9A 55 C6 E1 23 15 A6 43 2A
74 09 72 88 9E F0 4A C3 04 63 1A 8D 96 59 7F 38 83 8E A9 F5 03 C6 A9 27 18 94 C7 76 4C 99 87 BB
44 BA 26 D3 75 C6 64 D2 31 C6 84 15 8A A3 E4 88 3C 48 7F D3 5F 5A 11 E3 68 13 40 BE 58 BA 06 0E
```
where top 1504 bytes is the message need to be authenticated but last 32 bytes are HMAC-SHA256.

Keeping first 1504 bytes of the key blob and the derived HMAC-SHA256 key, we get such HMAC
`3118A94A8945C522560C8389F0BCE62333AE71A5BD704E4DB5DB71930A756F56`
which is not equal to
`44BA26D375C664D231C684158AA3E4883C487FD35F5A11E3681340BE58BA060E`

I double checked the reversed RW_* firmware how the key is derived and what part of the key blob is being authenticated. 

**Does this mean that there is a hidden top root key fused in the Titan M and accessible ONLY from the key ladder? And the key ladder internally concatenates this super secret key with the ROT, salt, and the RW_ FW bytes to derive the real HMAC key. Same is for the AES encryption/decryption.
If it is so, the leakage of above secrets used for deriving the KEK and HMAC keys doesn't compromise the whole system as an important part is still hidden in HW.**

**Comment by max-r-b** [comment]
I am closing this issue. Btw in our latest research we show how we leaked StrongBox keys using only one software vulnerability.
