### ISSUE TITLE
Typo/inaccuracy in the EU-21-Rossi_Bellom-2021_A_Titan_M_Odyssey.pdf paper

### ISSUE THREAD

**Issue by AlexeyGorbushin** [quarkslab/titanm#8]
The EU-21-Rossi_Bellom-2021_A_Titan_M_Odyssey.pdf paper has possible typo or inaccuracy in 'Key Blob structure' description, p. 49. 
The paper claims that last 32 bytes of the key blob starting from 0x5e0 offset is the SHA256 digest. But it is not so. It is HMAC-SHA256. 
I think it doesn't make sense to use just SHA256 there as just a hash doesn't guarantee the authenticity. But HMAC does.

**Comment by dmell** [comment]
Hello,

Thank you for your comment! The last 32 bytes are indeed an HMAC digest. I think this was a simple typo since the same slide shows the portion of key blob being authenticated. I will fix that right away.
